# if we specify python as language, travis will use virtualenv with
# --no-site-packages, which will mean the python-lxml library we need
# will not be found, and the tests will fail. so pretend we're a C
# language project instead to skip the virtualenv completely, which
# we don't really need anyway.

language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python3-lxml python3-mock

script: make test
